In [8]:
import numpy as np
import pandas as pd

In [11]:
#Create series
s = pd.Series([1,2,"Hello",4,-5,6,True,8,9,np.nan])
print(s)

0        1
1        2
2    Hello
3        4
4       -5
5        6
6     True
7        8
8        9
9      NaN
dtype: object

In [13]:
snum = pd.Series([1,2,3,4,5,6,7,8,9])
print(snum)
print(snum.sum())

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
45

In [14]:
#Bad Practice Validators
sbad = pd.Series([1,2,3,4,True,np.nan])
print(sbad.sum())
print(sbad.mean())

11
2.2

In [17]:
#Create DataFrame
DataF = pd.DataFrame({'a':[1,2,np.nan],
                  'b':[3,4,5],
                  'c': pd.Timestamp("20260101"),
                  'd': pd.Categorical(["Test","Train","Validate"]),
                  'e': pd.Series(1,index=list(range(3)), dtype = "int")})
print(DataF)

     a  b          c         d  e
0  1.0  3 2026-01-01      Test  1
1  2.0  4 2026-01-01     Train  1
2  NaN  5 2026-01-01  Validate  1

In [18]:
df = pd.read_csv(r"C:\Users\Lalaliao's\Downloads\ParisHousingClass.csv")
df

,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price,category
0,75523,3,0,1,63,9373,3,8,2005,0,1,4313,9005,956,0,7,7559081.5,Basic
1,80771,39,1,1,98,39381,8,6,2015,1,0,3653,2436,128,1,2,8085989.5,Luxury
2,55712,58,0,1,19,34457,6,8,2021,0,0,2937,8852,135,1,9,5574642.1,Basic
3,32316,47,0,0,6,27939,10,4,2012,0,1,659,7141,359,0,3,3232561.2,Luxury
4,70429,19,1,1,90,38045,3,7,1990,1,0,8435,2429,292,1,4,7055052.0,Luxury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1726,89,0,1,5,73133,7,6,2009,0,1,9311,1698,218,0,4,176425.9,Basic
9996,44403,29,1,1,12,34606,9,4,1990,0,1,9061,1742,230,0,0,4448474.0,Basic
9997,83841,3,0,0,69,80933,10,10,2005,1,1,8304,7730,345,1,9,8390030.5,Basic
9998,59036,70,0,0,96,55856,1,3,2010,0,1,2590,6174,339,1,4,5905107.0,Basic
9999,1440,84,0,0,49,18412,6,10,1994,1,0,8485,2024,278,1,6,146708.4,Basic

In [10]:
df.head()

,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price,category
0,75523,3,0,1,63,9373,3,8,2005,0,1,4313,9005,956,0,7,7559081.5,Basic
1,80771,39,1,1,98,39381,8,6,2015,1,0,3653,2436,128,1,2,8085989.5,Luxury
2,55712,58,0,1,19,34457,6,8,2021,0,0,2937,8852,135,1,9,5574642.1,Basic
3,32316,47,0,0,6,27939,10,4,2012,0,1,659,7141,359,0,3,3232561.2,Luxury
4,70429,19,1,1,90,38045,3,7,1990,1,0,8435,2429,292,1,4,7055052.0,Luxury

In [23]:
print(df.shape)
print(df.shape[0])
print(df.shape[1])

(10000, 18)
10000
18

In [20]:
df.columns

Index(['squareMeters', 'numberOfRooms', 'hasYard', 'hasPool', 'floors',
       'cityCode', 'cityPartRange', 'numPrevOwners', 'made', 'isNewBuilt',
       'hasStormProtector', 'basement', 'attic', 'garage', 'hasStorageRoom',
       'hasGuestRoom', 'price', 'category'],
      dtype='object')

In [21]:
df.describe()

,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.00000,10000.000000,10000.00000,1.000000e+04
mean,49870.13120,50.358400,0.508700,0.496800,50.276300,50225.486100,5.510100,5.521700,2005.48850,0.499100,0.499900,5033.103900,5028.01060,553.12120,0.503000,4.99460,4.993448e+06
std,28774.37535,28.816696,0.499949,0.500015,28.889171,29006.675799,2.872024,2.856667,9.30809,0.500024,0.500025,2876.729545,2894.33221,262.05017,0.500016,3.17641,2.877424e+06
min,89.00000,1.000000,0.000000,0.000000,1.000000,3.000000,1.000000,1.000000,1990.00000,0.000000,0.000000,0.000000,1.00000,100.00000,0.000000,0.00000,1.031350e+04
25%,25098.50000,25.000000,0.000000,0.000000,25.000000,24693.750000,3.000000,3.000000,1997.00000,0.000000,0.000000,2559.750000,2512.00000,327.75000,0.000000,2.00000,2.516402e+06
50%,50105.50000,50.000000,1.000000,0.000000,50.000000,50693.000000,5.000000,5.000000,2005.50000,0.000000,0.000000,5092.500000,5045.00000,554.00000,1.000000,5.00000,5.016180e+06
75%,74609.75000,75.000000,1.000000,1.000000,76.000000,75683.250000,8.000000,8.000000,2014.00000,1.000000,1.000000,7511.250000,7540.50000,777.25000,1.000000,8.00000,7.469092e+06
max,99999.00000,100.000000,1.000000,1.000000,100.000000,99953.000000,10.000000,10.000000,2021.00000,1.000000,1.000000,10000.000000,10000.00000,1000.00000,1.000000,10.00000,1.000677e+07

In [24]:
df["numberOfRooms"]

0        3
1       39
2       58
3       47
4       19
        ..
9995    89
9996    29
9997     3
9998    70
9999    84
Name: numberOfRooms, Length: 10000, dtype: int64

In [29]:
df["category"].value_counts()

category
Basic     7470
Luxury    2530
Name: count, dtype: int64

In [37]:
df_new = df.sort_values(by=['price'])
df_new[0:10]

,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price,category
4182,89,33,0,0,72,61648,3,4,1995,0,1,3114,1258,264,1,9,10313.5,Basic
4568,123,61,0,0,1,33633,9,1,2011,0,1,9390,6219,922,0,9,13229.1,Basic
3265,111,32,0,1,34,80623,1,4,2003,1,0,2239,2795,951,1,7,14431.3,Basic
7155,128,38,0,1,6,8862,6,2,1990,0,0,6861,5769,442,0,5,15488.0,Basic
2319,148,91,0,0,11,27008,6,9,1992,1,1,6618,7045,939,1,10,16799.2,Basic
7132,143,27,0,0,53,82480,5,2,2010,1,0,4426,5336,911,0,4,17071.0,Basic
2792,163,6,0,0,29,26761,4,3,1990,1,0,6022,8521,391,1,3,17363.0,Basic
2822,176,30,0,0,15,62932,6,3,2000,0,0,2325,6230,536,0,9,18985.0,Basic
3839,180,63,0,0,71,91418,2,2,2020,0,1,8598,3119,268,0,10,19638.0,Basic
4328,163,35,0,0,83,29281,7,6,1995,0,1,2675,6452,724,1,2,19788.5,Basic

In [31]:
#finding unique values\
df["category"].unique()
df.category.unique()

array(['Basic', 'Luxury'], dtype=object)

In [32]:
df["made"].unique()

array([2005, 2015, 2021, 2012, 1990, 1995, 2003, 1993, 2011, 2008, 2004,
       2018, 2009, 2013, 2016, 2017, 2000, 2019, 2020, 1994, 2014, 1998,
       2001, 1996, 1991, 1992, 1999, 1997, 2010, 2007, 2006, 2002])

In [33]:
#apply numpy and pandas
np.sort(df['made'].unique())

array([1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,
       2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])

In [34]:
print(df["isNewBuilt"])
print(df.isNewBuilt)

0       0
1       1
2       0
3       0
4       1
       ..
9995    0
9996    0
9997    1
9998    0
9999    1
Name: isNewBuilt, Length: 10000, dtype: int64
0       0
1       1
2       0
3       0
4       1
       ..
9995    0
9996    0
9997    1
9998    0
9999    1
Name: isNewBuilt, Length: 10000, dtype: int64

In [36]:
print(df[10:20])

    squareMeters  numberOfRooms  hasYard  hasPool  floors  cityCode  \
10         23563             21        0        1      90     91058
11         96470             74        1        0      21     92029
12         19127             31        1        0       5      7475
13         13087             44        1        0      77     40475
14         79770              3        0        1      69     54812
15         75985             60        1        0      67      6517
16         64169             88        0        1       6     61711
17         99371             31        1        1      16     96297
18         25966             37        1        1      17     22818
19         41792             43        1        1      10     80768

    cityPartRange  numPrevOwners  made  isNewBuilt  hasStormProtector  \
10              6              8  1993           1                  0
11              4              2  2011           1                  1
12              2              9  2008           0                  0
13              8              4  2004           1                  0
14             10              5  2018           0                  1
15              6              9  2009           1                  1
16              3              9  2011           1                  1
17              7              8  2013           1                  1
18              3              1  2016           0                  0
19              9              5  2017           1                  1

    basement  attic  garage  hasStorageRoom  hasGuestRoom      price category
10       703    852     684               1            10  2366397.3    Basic
11      5414   1172     716               1             9  9652258.1   Luxury
12      5387   4430     374               0             4  1914688.8    Basic
13      1745    724     582               0             0  1320803.4   Luxury
14      8871   7117     240               0             7  7986665.8    Basic
15      4878    281     384               1             5  7607322.9   Luxury
16      3054    129     726               0             9  6420823.1    Basic
17      3258   6296     354               1             8  9944705.3   Luxury
18      8257   2557     162               0             6  2604486.6    Basic
19      2950   9573     572               1             5  4187667.7   Luxury

In [40]:
df_new_reset = df_new.reset_index(drop = True)
df_new_reset

,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price,category
0,89,33,0,0,72,61648,3,4,1995,0,1,3114,1258,264,1,9,10313.5,Basic
1,123,61,0,0,1,33633,9,1,2011,0,1,9390,6219,922,0,9,13229.1,Basic
2,111,32,0,1,34,80623,1,4,2003,1,0,2239,2795,951,1,7,14431.3,Basic
3,128,38,0,1,6,8862,6,2,1990,0,0,6861,5769,442,0,5,15488.0,Basic
4,148,91,0,0,11,27008,6,9,1992,1,1,6618,7045,939,1,10,16799.2,Basic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,99952,41,1,0,69,51336,10,7,2000,0,1,1285,7588,192,1,9,9998411.0,Basic
9996,99886,83,1,1,37,32438,5,8,2003,0,0,4600,7789,210,0,2,9999687.3,Basic
9997,99918,57,1,1,58,33628,1,8,1990,0,0,2482,3894,155,0,4,10002945.0,Basic
9998,99985,20,0,0,77,28887,9,5,2003,0,1,3025,6669,354,1,1,10004278.3,Basic
9999,99999,58,0,0,68,10477,3,4,2012,1,1,7631,4199,776,0,2,10006771.2,Basic

In [44]:
df.loc[10:20,['cityCode','made']]

    cityCode  made
10     91058  1993
11     92029  2011
12      7475  2008
13     40475  2004
14     54812  2018
15      6517  2009
16     61711  2011
17     96297  2013
18     22818  2016
19     80768  2017
20     97667  2009

In [46]:
df.iloc[10:20,[5,2]]

    cityCode  hasYard
10     91058        0
11     92029        1
12      7475        1
13     40475        1
14     54812        0
15      6517        1
16     61711        0
17     96297        1
18     22818        1
19     80768        1

In [51]:
(df.loc[10:20,['floors']].describe())

          floors
count  11.000000
mean   38.909091
std    32.051379
min     5.000000
25%    13.000000
50%    21.000000
75%    68.000000
max    90.000000

In [53]:
print(df[df["price"] > 4000000])

      squareMeters  numberOfRooms  hasYard  hasPool  floors  cityCode  \
0            75523              3        0        1      63      9373
1            80771             39        1        1      98     39381
2            55712             58        0        1      19     34457
4            70429             19        1        1      90     38045
6            58682             10        1        1      99      6450
...            ...            ...      ...      ...     ...       ...
9989         90996             81        1        1      80      1085
9991         96173             12        1        0      36     36812
9996         44403             29        1        1      12     34606
9997         83841              3        0        0      69     80933
9998         59036             70        0        0      96     55856

      cityPartRange  numPrevOwners  made  isNewBuilt  hasStormProtector  \
0                 3              8  2005           0                  1
1                 8              6  2015           1                  0
2                 6              8  2021           0                  0
4                 3              7  1990           1                  0
6                10              9  1995           1                  1
...             ...            ...   ...         ...                ...
9989              3              9  1990           0                  1
9991              7              7  2015           1                  1
9996              9              4  1990           0                  1
9997             10             10  2005           1                  1
9998              1              3  2010           0                  1

      basement  attic  garage  hasStorageRoom  hasGuestRoom      price  \
0         4313   9005     956               0             7  7559081.5
1         3653   2436     128               1             2  8085989.5
2         2937   8852     135               1             9  5574642.1
4         8435   2429     292               1             4  7055052.0
6         5930   9453     848               0             5  5876376.5
...        ...    ...     ...             ...           ...        ...
9989      8633   2007     689               0             5  9112369.0
9991       837   3716     564               0             9  9623811.5
9996      9061   1742     230               0             0  4448474.0
9997      8304   7730     345               1             9  8390030.5
9998      2590   6174     339               1             4  5905107.0

     category
0       Basic
1      Luxury
2       Basic
4      Luxury
6      Luxury
...       ...
9989    Basic
9991   Luxury
9996    Basic
9997    Basic
9998    Basic

[6031 rows x 18 columns]

In [54]:
df[df["isNewBuilt"]==1]['squareMeters'].mean()

np.float64(49562.65377679824)

In [57]:
newbuilt = df['isNewBuilt'] == 1
expensive = df['price'] > 4000000

df.loc[newbuilt & expensive]['category'].value_counts(normalize = True)

category
Basic     0.50384
Luxury    0.49616
Name: proportion, dtype: float64

In [63]:
df['category'].value_counts()

category
Basic     7470
Luxury    2530
Name: count, dtype: int64

In [67]:
oldbuilt = df['isNewBuilt'] == 0
expensivevery = df['price'] > 4000000

df.loc[oldbuilt & expensivevery]['category'].value_counts()

category
Basic     3035
Luxury       1
Name: count, dtype: int64

In [69]:
#Normalization
year = df['made'] <=2000
expensive = df['price'] > 4000000

df.loc[year & expensive]['category'].value_counts(normalize = True)

category
Basic     0.754266
Luxury    0.245734
Name: proportion, dtype: float64

In [74]:
#customized functions for BE year change
df['made_BE'] = df['made'] + 543
print(df)

      squareMeters  numberOfRooms  hasYard  hasPool  floors  cityCode  \
0            75523              3        0        1      63      9373
1            80771             39        1        1      98     39381
2            55712             58        0        1      19     34457
3            32316             47        0        0       6     27939
4            70429             19        1        1      90     38045
...            ...            ...      ...      ...     ...       ...
9995          1726             89        0        1       5     73133
9996         44403             29        1        1      12     34606
9997         83841              3        0        0      69     80933
9998         59036             70        0        0      96     55856
9999          1440             84        0        0      49     18412

      cityPartRange  numPrevOwners  made  isNewBuilt  hasStormProtector  \
0                 3              8  2005           0                  1
1                 8              6  2015           1                  0
2                 6              8  2021           0                  0
3                10              4  2012           0                  1
4                 3              7  1990           1                  0
...             ...            ...   ...         ...                ...
9995              7              6  2009           0                  1
9996              9              4  1990           0                  1
9997             10             10  2005           1                  1
9998              1              3  2010           0                  1
9999              6             10  1994           1                  0

      basement  attic  garage  hasStorageRoom  hasGuestRoom      price  \
0         4313   9005     956               0             7  7559081.5
1         3653   2436     128               1             2  8085989.5
2         2937   8852     135               1             9  5574642.1
3          659   7141     359               0             3  3232561.2
4         8435   2429     292               1             4  7055052.0
...        ...    ...     ...             ...           ...        ...
9995      9311   1698     218               0             4   176425.9
9996      9061   1742     230               0             0  4448474.0
9997      8304   7730     345               1             9  8390030.5
9998      2590   6174     339               1             4  5905107.0
9999      8485   2024     278               1             6   146708.4

     category  made_BE
0       Basic     2548
1      Luxury     2558
2       Basic     2564
3      Luxury     2555
4      Luxury     2533
...       ...      ...
9995    Basic     2552
9996    Basic     2533
9997    Basic     2548
9998    Basic     2553
9999    Basic     2537

[10000 rows x 19 columns]

In [76]:
def convertBE(x):
    return x + 543

df['made_function'] = df['made'].apply(convertBE)
print(df)

      squareMeters  numberOfRooms  hasYard  hasPool  floors  cityCode  \
0            75523              3        0        1      63      9373
1            80771             39        1        1      98     39381
2            55712             58        0        1      19     34457
3            32316             47        0        0       6     27939
4            70429             19        1        1      90     38045
...            ...            ...      ...      ...     ...       ...
9995          1726             89        0        1       5     73133
9996         44403             29        1        1      12     34606
9997         83841              3        0        0      69     80933
9998         59036             70        0        0      96     55856
9999          1440             84        0        0      49     18412

      cityPartRange  numPrevOwners  made  isNewBuilt  hasStormProtector  \
0                 3              8  2005           0                  1
1                 8              6  2015           1                  0
2                 6              8  2021           0                  0
3                10              4  2012           0                  1
4                 3              7  1990           1                  0
...             ...            ...   ...         ...                ...
9995              7              6  2009           0                  1
9996              9              4  1990           0                  1
9997             10             10  2005           1                  1
9998              1              3  2010           0                  1
9999              6             10  1994           1                  0

      basement  attic  garage  hasStorageRoom  hasGuestRoom      price  \
0         4313   9005     956               0             7  7559081.5
1         3653   2436     128               1             2  8085989.5
2         2937   8852     135               1             9  5574642.1
3          659   7141     359               0             3  3232561.2
4         8435   2429     292               1             4  7055052.0
...        ...    ...     ...             ...           ...        ...
9995      9311   1698     218               0             4   176425.9
9996      9061   1742     230               0             0  4448474.0
9997      8304   7730     345               1             9  8390030.5
9998      2590   6174     339               1             4  5905107.0
9999      8485   2024     278               1             6   146708.4

     category  made_BE  made_function
0       Basic     2548           2548
1      Luxury     2558           2558
2       Basic     2564           2564
3      Luxury     2555           2555
4      Luxury     2533           2533
...       ...      ...            ...
9995    Basic     2552           2552
9996    Basic     2533           2533
9997    Basic     2548           2548
9998    Basic     2553           2553
9999    Basic     2537           2537

[10000 rows x 20 columns]

In [77]:
df["labelhaspool"] = df['hasPool'].apply(lambda x: "Yes" if x == 1 else "No")

In [ ]:
def label_pool(x):
    if x == 1:
        return "Yes"
    else:
        return "No"
df['label2haspool'] = df['hasPool'].apply(label_pool)

In [81]:
df.groupby(['category','hasYard','labelhaspool'])['price'].mean()

category  hasYard  labelhaspool
Basic     0        No              5.062912e+06
                   Yes             4.963695e+06
          1        No              4.992802e+06
                   Yes             5.085154e+06
Luxury    0        No              4.616997e+06
                   Yes             8.765305e+05
          1        No              4.915307e+06
                   Yes             4.907938e+06
Name: price, dtype: float64

In [88]:
#find out how many houses based on categories have installed a storm protector
df.groupby("category")['hasStormProtector'].value_counts()

category  hasStormProtector
Basic     1                    3759
          0                    3711
Luxury    0                    1290
          1                    1240
Name: count, dtype: int64

In [90]:
#find what minimum area size of house base on categories
df.groupby("category")["squareMeters"].describe()

,count,mean,std,min,25%,50%,75%,max
category,,,,,,,,
Basic,7470.0,50171.232129,28755.123301,89.0,25335.0,50478.5,74878.75,99999.0
Luxury,2530.0,48981.109881,28818.476839,152.0,24157.5,48675.5,73910.00,99913.0

In [93]:
#find out how many houses based on categories and new built + stormprotector
df.groupby(['category','isNewBuilt'])['hasStormProtector'].value_counts()

category  isNewBuilt  hasStormProtector
Basic     0           0                    2511
                      1                    2491
          1           1                    1268
                      0                    1200
Luxury    0           1                       5
                      0                       2
          1           0                    1288
                      1                    1235
Name: count, dtype: int64

In [95]:
split_df = np.array_split(df,4)
print(split_df)

[      squareMeters  numberOfRooms  hasYard  hasPool  floors  cityCode  \
0            75523              3        0        1      63      9373
1            80771             39        1        1      98     39381
2            55712             58        0        1      19     34457
3            32316             47        0        0       6     27939
4            70429             19        1        1      90     38045
...            ...            ...      ...      ...     ...       ...
2495         61856             17        1        0      97     36122
2496          2685             31        1        1      35     59357
2497         24021              4        1        0       4      8686
2498         72068             71        1        1      95     71948
2499         74729             92        1        1      59     15630

      cityPartRange  numPrevOwners  made  isNewBuilt  ...  basement  attic  \
0                 3              8  2005           0  ...      4313   9005
1                 8              6  2015           1  ...      3653   2436
2                 6              8  2021           0  ...      2937   8852
3                10              4  2012           0  ...       659   7141
4                 3              7  1990           1  ...      8435   2429
...             ...            ...   ...         ...  ...       ...    ...
2495              8              1  1999           1  ...      8735   4950
2496              6              1  2010           1  ...      5553   5076
2497              2              7  1997           1  ...       804   6439
2498              9              6  1992           0  ...      3751   2724
2499              2              9  2000           1  ...      5584   3958

      garage  hasStorageRoom  hasGuestRoom      price  category made_BE  \
0        956               0             7  7559081.5     Basic    2548
1        128               1             2  8085989.5    Luxury    2558
2        135               1             9  5574642.1     Basic    2564
3        359               0             3  3232561.2    Luxury    2555
4        292               1             4  7055052.0    Luxury    2533
...      ...             ...           ...        ...       ...     ...
2495     887               1             8  6199110.9    Luxury    2542
2496     188               0             9   274819.0    Luxury    2553
2497     354               1             9  2407456.7    Luxury    2540
2498     991               0             8  7221629.2     Basic    2535
2499     274               1             1  7486919.0    Luxury    2543

      made_function  labelhaspool
0              2548           Yes
1              2558           Yes
2              2564           Yes
3              2555            No
4              2533           Yes
...             ...           ...
2495           2542            No
2496           2553           Yes
2497           2540            No
2498           2535           Yes
2499           2543           Yes

[2500 rows x 21 columns],       squareMeters  numberOfRooms  hasYard  hasPool  floors  cityCode  \
2500         45242             27        0        0      56     80016
2501           350             65        0        0      40     30809
2502         42179             11        0        0      40     69102
2503         71973             32        0        1       9     21039
2504         19237             62        0        0      89     51495
...            ...            ...      ...      ...     ...       ...
4995         65479             82        0        1      48     95180
4996         47583             48        0        0      99     31744
4997         93184             78        0        0      43     13054
4998          1254             38        0        0      57     74479
4999         95328             59        1        1      24     28949

      cityPartRange  numPrevOwners  made  isNewBuilt  ...  basement  attic  \
2500              8              9  2003           1  ...       529   4812
2501              5              7  2020           1  ...      9872   5678
2502              6              3  1999           1  ...      9985    309
2503             10              3  2012           0  ...      2596   3306
2504              5              3  2012           0  ...      4135    613
...             ...            ...   ...         ...  ...       ...    ...
4995              5              7  1990           1  ...      2907   4270
4996              8             10  1992           1  ...      3705   8486
4997              7              5  1992           1  ...      3946   4450
4998              1              1  2001           0  ...      9002   6342
4999              8             10  2020           0  ...      8716   2131

      garage  hasStorageRoom  hasGuestRoom      price  category made_BE  \
2500     120               1             9  4527632.3     Basic    2546
2501     345               0             3    37972.0     Basic    2563
2502     442               1             7  4221359.9     Basic    2542
2503     575               1             1  7201696.2     Basic    2555
2504     888               1             8  1931115.2     Basic    2555
...      ...             ...           ...        ...       ...     ...
4995     111               1             9  6553618.0     Basic    2533
4996     983               0             1  4762269.2     Basic    2535
4997     159               0             9  9321499.2     Basic    2535
4998     283               1             7   128928.1     Basic    2544
4999     269               1             9  9538747.0     Basic    2563

      made_function  labelhaspool
2500           2546            No
2501           2563            No
2502           2542            No
2503           2555           Yes
2504           2555            No
...             ...           ...
4995           2533           Yes
4996           2535            No
4997           2535            No
4998           2544            No
4999           2563           Yes

[2500 rows x 21 columns],       squareMeters  numberOfRooms  hasYard  hasPool  floors  cityCode  \
5000          7388             75        0        1      96     35787
5001         34555             35        1        1      45     41312
5002         61310             49        0        0      21     55836
5003         20714             61        1        1      83     71535
5004         94704             55        1        1       6     84914
...            ...            ...      ...      ...     ...       ...
7495         87146              8        1        0      90      2593
7496         68010              1        1        1      71     65943
7497         12480              2        1        0      55     77588
7498         76231             24        1        1      89     32609
7499         46525             14        1        1      66     48097

      cityPartRange  numPrevOwners  made  isNewBuilt  ...  basement  attic  \
5000              4              4  2018           1  ...      4898   1814
5001              6             10  2003           1  ...      1597   5925
5002              5              5  2006           0  ...      5865   3866
5003              3              5  1993           1  ...      9406   9087
5004              5              7  2007           0  ...      3351   6903
...             ...            ...   ...         ...  ...       ...    ...
7495              7              8  2001           0  ...      8177   4527
7496              1              1  2010           1  ...       612   1124
7497              5              1  2015           1  ...      3084   7686
7498              7              4  2009           0  ...      9882   5348
7499              6             10  1999           0  ...      8748   9734

      garage  hasStorageRoom  hasGuestRoom      price  category made_BE  \
5000     366               1             7   750538.8     Basic    2561
5001     286               1             2  3467129.3    Luxury    2546
5002     618               0            10  6132679.6     Basic    2549
5003     277               0             9  2077129.3    Luxury    2536
5004     815               0             4  9480933.7     Basic    2550
...      ...             ...           ...        ...       ...     ...
7495     210               1             9  8725424.1     Basic    2544
7496     769               0             9  6812854.0    Luxury    2553
7497     578               0             5  1251446.5    Luxury    2558
7498     335               1             8  7633398.9     Basic    2552
7499     496               1             7  4662730.9     Basic    2542

      made_function  labelhaspool
5000           2561           Yes
5001           2546           Yes
5002           2549            No
5003           2536           Yes
5004           2550           Yes
...             ...           ...
7495           2544            No
7496           2553           Yes
7497           2558            No
7498           2552           Yes
7499           2542           Yes

[2500 rows x 21 columns],       squareMeters  numberOfRooms  hasYard  hasPool  floors  cityCode  \
7500          6807             53        0        1      19     96312
7501         40077             85        1        0      90     51219
7502         82519             97        0        1      93     76104
7503         21038             15        1        0      90     44209
7504         21751             71        0        0      82     78642
...            ...            ...      ...      ...     ...       ...
9995          1726             89        0        1       5     73133
9996         44403             29        1        1      12     34606
9997         83841              3        0        0      69     80933
9998         59036             70        0        0      96     55856
9999          1440             84        0        0      49     18412

      cityPartRange  numPrevOwners  made  isNewBuilt  ...  basement  attic  \
7500              3              3  2008           1  ...      2693   8767
7501              7              6  2011           1  ...      2350   5903
7502              3              5  2002           0  ...      7446   4137
7503              7              6  2007           0  ...      7527   4132
7504              6              8  1995           1  ...       782   7203
...             ...            ...   ...         ...  ...       ...    ...
9995              7              6  2009           0  ...      9311   1698
9996              9              4  1990           0  ...      9061   1742
9997             10             10  2005           1  ...      8304   7730
9998              1              3  2010           0  ...      2590   6174
9999              6             10  1994           1  ...      8485   2024

      garage  hasStorageRoom  hasGuestRoom      price  category made_BE  \
7500     503               0             0   687517.8     Basic    2551
7501     935               0             5  4020046.1    Luxury    2554
7502     815               0             0  8259491.2     Basic    2545
7503     365               0             0  2110409.7     Basic    2550
7504     583               0             8  2178623.5     Basic    2538
...      ...             ...           ...        ...       ...     ...
9995     218               0             4   176425.9     Basic    2552
9996     230               0             0  4448474.0     Basic    2533
9997     345               1             9  8390030.5     Basic    2548
9998     339               1             4  5905107.0     Basic    2553
9999     278               1             6   146708.4     Basic    2537

      made_function  labelhaspool
7500           2551           Yes
7501           2554            No
7502           2545           Yes
7503           2550            No
7504           2538            No
...             ...           ...
9995           2552           Yes
9996           2533           Yes
9997           2548            No
9998           2553            No
9999           2537            No

[2500 rows x 21 columns]]
4

C:\Anaconda3\Lib\site-packages\numpy\_core\fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [97]:
print(len(split_df))
split_df[1].loc[2500,:]

4

squareMeters             45242
numberOfRooms               27
hasYard                      0
hasPool                      0
floors                      56
cityCode                 80016
cityPartRange                8
numPrevOwners                9
made                      2003
isNewBuilt                   1
hasStormProtector            0
basement                   529
attic                     4812
garage                     120
hasStorageRoom               1
hasGuestRoom                 9
price                4527632.3
category                 Basic
made_BE                   2546
made_function             2546
labelhaspool                No
Name: 2500, dtype: object

In [113]:
concat_default = pd.concat([split_df[1],split_df[3]])
concat_default = concat_default.reset_index(drop=True)
print(concat_default)

      squareMeters  numberOfRooms  hasYard  hasPool  floors  cityCode  \
0            45242             27        0        0      56     80016
1              350             65        0        0      40     30809
2            42179             11        0        0      40     69102
3            71973             32        0        1       9     21039
4            19237             62        0        0      89     51495
...            ...            ...      ...      ...     ...       ...
4995          1726             89        0        1       5     73133
4996         44403             29        1        1      12     34606
4997         83841              3        0        0      69     80933
4998         59036             70        0        0      96     55856
4999          1440             84        0        0      49     18412

      cityPartRange  numPrevOwners  made  isNewBuilt  ...  basement  attic  \
0                 8              9  2003           1  ...       529   4812
1                 5              7  2020           1  ...      9872   5678
2                 6              3  1999           1  ...      9985    309
3                10              3  2012           0  ...      2596   3306
4                 5              3  2012           0  ...      4135    613
...             ...            ...   ...         ...  ...       ...    ...
4995              7              6  2009           0  ...      9311   1698
4996              9              4  1990           0  ...      9061   1742
4997             10             10  2005           1  ...      8304   7730
4998              1              3  2010           0  ...      2590   6174
4999              6             10  1994           1  ...      8485   2024

      garage  hasStorageRoom  hasGuestRoom      price  category made_BE  \
0        120               1             9  4527632.3     Basic    2546
1        345               0             3    37972.0     Basic    2563
2        442               1             7  4221359.9     Basic    2542
3        575               1             1  7201696.2     Basic    2555
4        888               1             8  1931115.2     Basic    2555
...      ...             ...           ...        ...       ...     ...
4995     218               0             4   176425.9     Basic    2552
4996     230               0             0  4448474.0     Basic    2533
4997     345               1             9  8390030.5     Basic    2548
4998     339               1             4  5905107.0     Basic    2553
4999     278               1             6   146708.4     Basic    2537

      made_function  labelhaspool
0              2546            No
1              2563            No
2              2542            No
3              2555           Yes
4              2555            No
...             ...           ...
4995           2552           Yes
4996           2533           Yes
4997           2548            No
4998           2553            No
4999           2537            No

[5000 rows x 21 columns]

In [114]:
concat_def2 = pd.concat([split_df[1],split_df[3]], join = 'inner')
concat_def2

,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,...,basement,attic,garage,hasStorageRoom,hasGuestRoom,price,category,made_BE,made_function,labelhaspool
2500,45242,27,0,0,56,80016,8,9,2003,1,...,529,4812,120,1,9,4527632.3,Basic,2546,2546,No
2501,350,65,0,0,40,30809,5,7,2020,1,...,9872,5678,345,0,3,37972.0,Basic,2563,2563,No
2502,42179,11,0,0,40,69102,6,3,1999,1,...,9985,309,442,1,7,4221359.9,Basic,2542,2542,No
2503,71973,32,0,1,9,21039,10,3,2012,0,...,2596,3306,575,1,1,7201696.2,Basic,2555,2555,Yes
2504,19237,62,0,0,89,51495,5,3,2012,0,...,4135,613,888,1,8,1931115.2,Basic,2555,2555,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1726,89,0,1,5,73133,7,6,2009,0,...,9311,1698,218,0,4,176425.9,Basic,2552,2552,Yes
9996,44403,29,1,1,12,34606,9,4,1990,0,...,9061,1742,230,0,0,4448474.0,Basic,2533,2533,Yes
9997,83841,3,0,0,69,80933,10,10,2005,1,...,8304,7730,345,1,9,8390030.5,Basic,2548,2548,No
9998,59036,70,0,0,96,55856,1,3,2010,0,...,2590,6174,339,1,4,5905107.0,Basic,2553,2553,No
9999,1440,84,0,0,49,18412,6,10,1994,1,...,8485,2024,278,1,6,146708.4,Basic,2537,2537,No

In [119]:
tester_df = pd.DataFrame({'A':[1,2],'B':["Yes","No"],'C':[3,4]})
test_df2 = pd.DataFrame({'C':[7,4],'D':['x','y'],'E':[5,6]})

pd.merge(tester_df, test_df2, how = 'right')

     A    B  C  D  E
0  NaN  NaN  7  x  5
1  2.0   No  4  y  6

In [ ]:
join_data = split_df[2].join(split_df[3], how = 'left', left_on = ['category'], right_on = ['isNewBuilt'])