In [ ]:
#Set 1 : Preparation from the Class 14

In [2]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv(r"C:\Users\Lalaliao's\Downloads\ds_salaries.csv")

In [8]:
df.shape

(607, 12)

In [11]:
df.head(10)

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
5,5,2020,EN,FT,Data Analyst,72000,USD,72000,US,100,US,L
6,6,2020,SE,FT,Lead Data Scientist,190000,USD,190000,US,100,US,S
7,7,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L
8,8,2020,MI,FT,Business Data Analyst,135000,USD,135000,US,100,US,L
9,9,2020,SE,FT,Lead Data Engineer,125000,USD,125000,NZ,50,NZ,S

In [13]:
df.tail(5)

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [16]:
df.tail(5).to_csv(r"C:\Users\Lalaliao's\Desktop\submission.csv")

In [19]:
print(df["experience_level"].dtypes)

object

In [20]:
print(df["salary"].dtypes)

int64

In [22]:
df["job_title"].unique().shape

(50,)

In [45]:
df["job_title"].value_counts().head(10)

job_title
Data Scientist                143
Data Engineer                 132
Data Analyst                   97
Machine Learning Engineer      41
Research Scientist             16
Data Science Manager           12
Data Architect                 11
Big Data Engineer               8
Machine Learning Scientist      8
Principal Data Scientist        7
Name: count, dtype: int64

In [27]:
#‘Entry-level’, ‘Mid-level’, ‘Senior-level’, ‘Executive-level
#S=’Small’, M=’Medium’, L=’Large’)
df['experience_level'] = df['experience_level'].replace({'EN' : 'Entry-level' ,'MI' : 'Mid-level',
                                                                  'SE' : 'Senior-level','EX' : 'Executive-level'})
df['company_size'] = df['company_size'].replace({'S' : 'Small', 'M' : 'Medium', 'L' : 'Large'})
df.to_csv(r"C:\Users\Lalaliao's\Desktop\submissionChangeName.csv", index = False)

In [38]:
#What data types for each columns and check if there are any missing (null) values?
for col in df.columns:
    print("{}, type {}".format(col, df[col].dtypes))

Unnamed: 0, type int64
work_year, type int64
experience_level, type object
employment_type, type object
job_title, type object
salary, type int64
salary_currency, type object
salary_in_usd, type int64
employee_residence, type object
remote_ratio, type int64
company_location, type object
company_size, type object

In [40]:
#find missing values (single)
df['experience_level'].isnull().sum()

np.int64(0)

In [43]:
#find missing values (multiple)
for col in df.columns:
    missing = df[col].isna().sum()
    print("{}, have missing values {}".format(col, missing))

Unnamed: 0, have missing values 0
work_year, have missing values 0
experience_level, have missing values 0
employment_type, have missing values 0
job_title, have missing values 0
salary, have missing values 0
salary_currency, have missing values 0
salary_in_usd, have missing values 0
employee_residence, have missing values 0
remote_ratio, have missing values 0
company_location, have missing values 0
company_size, have missing values 0

In [57]:
#Filter the dataset to show only employees who have a salary_in_usd strictly greater than $100,000. 
#What percentage of the total dataset does this represent?
personfilter = df.loc[df['salary_in_usd'] > 100000].shape[0]
allperson = df.shape[0]

print((personfilter / allperson)*100)

50.24711696869851

In [62]:
#Find all records of the “Data Scientists” who work for “Large” companies fully remotely (remote_ratio = 100)
df.loc[(df["job_title"] == "Data Scientist") &
(df["company_size"] == "Large") &
(df["remote_ratio"] == 100)]

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
32,32,2020,Senior-level,FT,Data Scientist,60000,EUR,68428,GR,100,US,Large
48,48,2020,Mid-level,FT,Data Scientist,105000,USD,105000,US,100,US,Large
63,63,2020,Senior-level,FT,Data Scientist,412000,USD,412000,US,100,US,Large
116,116,2021,Mid-level,FT,Data Scientist,50000,USD,50000,NG,100,NG,Large
152,152,2021,Mid-level,FT,Data Scientist,95000,CAD,75774,CA,100,CA,Large
153,153,2021,Entry-level,FT,Data Scientist,13400,USD,13400,UA,100,UA,Large
177,177,2021,Mid-level,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,Large
202,202,2021,Mid-level,FT,Data Scientist,32000,EUR,37825,ES,100,ES,Large
204,204,2021,Mid-level,FT,Data Scientist,160000,USD,160000,US,100,US,Large
240,240,2021,Senior-level,FT,Data Scientist,130000,CAD,103691,CA,100,CA,Large
243,243,2021,Senior-level,FT,Data Scientist,165000,USD,165000,US,100,US,Large
398,398,2022,Senior-level,FT,Data Scientist,215300,USD,215300,US,100,US,Large
399,399,2022,Senior-level,FT,Data Scientist,158200,USD,158200,US,100,US,Large
459,459,2022,Mid-level,FT,Data Scientist,2400000,INR,31615,IN,100,IN,Large
492,492,2022,Mid-level,FT,Data Scientist,150000,PLN,35590,PL,100,PL,Large
499,499,2022,Entry-level,FT,Data Scientist,66500,CAD,52396,CA,100,CA,Large
502,502,2022,Entry-level,FT,Data Scientist,40000,USD,40000,JP,100,MY,Large
524,524,2022,Mid-level,FT,Data Scientist,135000,USD,135000,US,100,US,Large

In [72]:
#Use numpy functions or pandas functions to find the row with the absolute highest salary_in_usd.
#What is the job title and experience level of this person
maxperson = df.loc[df["salary_in_usd"] == df['salary_in_usd'].max()].index[0]
df.iloc[maxperson]['job_title']

'Principal Data Engineer'

In [76]:
#Find all rows where the employee_residence is different from the company_location. 
#How many such employees are there?
df.loc[df['employee_residence'] != df['company_location']]

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
17,17,2020,Senior-level,FT,Big Data Engineer,100000,EUR,114047,PL,100,GB,Small
19,19,2020,Mid-level,FT,Lead Data Engineer,56000,USD,56000,PT,100,US,Medium
32,32,2020,Senior-level,FT,Data Scientist,60000,EUR,68428,GR,100,US,Large
40,40,2020,Mid-level,FT,Data Scientist,45760,USD,45760,PH,100,US,Small
53,53,2020,Entry-level,FT,Data Engineer,48000,EUR,54742,PK,100,DE,Large
54,54,2020,Senior-level,FL,Computer Vision Engineer,60000,USD,60000,RU,100,US,Small
61,61,2020,Mid-level,FT,Data Engineer,130800,USD,130800,ES,100,US,Medium
70,70,2020,Mid-level,FT,Data Scientist,55000,EUR,62726,FR,50,LU,Small
73,73,2021,Executive-level,FT,BI Data Analyst,150000,USD,150000,IN,100,US,Large
82,82,2021,Mid-level,FT,Applied Data Scientist,68000,CAD,54238,GB,50,CA,Large
84,84,2021,Executive-level,FT,Director of Data Science,130000,EUR,153667,IT,100,PL,Large
89,89,2021,Senior-level,FT,Data Analyst,80000,USD,80000,BG,100,US,Small
90,90,2021,Senior-level,FT,Marketing Data Analyst,75000,EUR,88654,GR,100,DK,Large
96,96,2021,Entry-level,PT,AI Scientist,12000,USD,12000,BR,100,US,Small
99,99,2021,Mid-level,FT,Computer Vision Software Engineer,81000,EUR,95746,DE,100,US,Small
102,102,2021,Mid-level,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,Large
113,113,2021,Entry-level,PT,AI Scientist,12000,USD,12000,PK,100,US,Medium
120,120,2021,Mid-level,FT,Big Data Engineer,60000,USD,60000,ES,50,RO,Medium
132,132,2021,Mid-level,FT,Applied Machine Learning Scientist,38400,USD,38400,VN,100,US,Medium
149,149,2021,Senior-level,FT,Cloud Data Engineer,160000,USD,160000,BR,100,US,Small
156,156,2021,Mid-level,FT,Data Scientist,160000,SGD,119059,SG,100,IL,Medium
179,179,2021,Mid-level,FT,Data Scientist,420000,INR,5679,IN,100,US,Small
182,182,2021,Mid-level,FT,Data Engineer,22000,EUR,26005,RO,0,US,Large
186,186,2021,Senior-level,FT,Data Analytics Engineer,50000,USD,50000,VN,100,GB,Medium
187,187,2021,Executive-level,FT,Data Science Consultant,59000,EUR,69741,FR,100,ES,Small
188,188,2021,Senior-level,FT,Data Engineer,65000,EUR,76833,RO,50,GB,Small
190,190,2021,Senior-level,FT,Data Science Manager,152000,USD,152000,US,100,FR,Large
198,198,2021,Senior-level,FT,Data Science Manager,4000000,INR,54094,IN,50,US,Large
200,200,2021,Mid-level,FT,Data Scientist,52000,EUR,61467,DE,50,AT,Medium
203,203,2021,Senior-level,FT,Research Scientist,50000,USD,50000,FR,100,US,Small
208,208,2021,Mid-level,FL,Data Engineer,20000,USD,20000,IT,0,US,Large
212,212,2021,Mid-level,FT,Data Engineer,48000,GBP,66022,HK,50,GB,Small
213,213,2021,Entry-level,FT,Big Data Engineer,435000,INR,5882,IN,0,CH,Large
224,224,2021,Senior-level,FT,Machine Learning Scientist,225000,USD,225000,US,100,CA,Large
244,244,2021,Entry-level,FT,AI Scientist,1335000,INR,18053,IN,100,AS,Small
264,264,2021,Mid-level,FT,Data Scientist,21600,EUR,25532,RS,100,DE,Small
265,265,2021,Senior-level,FT,Lead Data Engineer,160000,USD,160000,PR,50,US,Small
273,273,2021,Entry-level,FT,Machine Learning Engineer,85000,USD,85000,NL,100,DE,Small
281,281,2021,Entry-level,FT,Research Scientist,100000,USD,100000,JE,0,CN,Large
396,396,2022,Mid-level,FT,Machine Learning Engineer,80000,EUR,87932,FR,100,DE,Medium
417,417,2022,Senior-level,FT,Data Science Engineer,60000,USD,60000,AR,100,MX,Large
488,488,2022,Mid-level,FL,Data Scientist,100000,USD,100000,CA,100,US,Medium
489,489,2022,Entry-level,CT,Applied Machine Learning Scientist,29000,EUR,31875,TN,100,CZ,Medium
490,490,2022,Senior-level,FT,Head of Data,200000,USD,200000,MY,100,US,Medium
494,494,2022,Senior-level,FT,Data Scientist,100000,USD,100000,BR,100,US,Medium
496,496,2022,Entry-level,FT,Data Engineer,52800,EUR,58035,PK,100,DE,Medium
502,502,2022,Entry-level,FT,Data Scientist,40000,USD,40000,JP,100,MY,Large
506,506,2022,Mid-level,FT,Applied Machine Learning Scientist,75000,USD,75000,BO,100,US,Large
515,515,2022,Mid-level,FT,Data Scientist,48000,USD,48000,RU,100,US,Small
521,521,2022,Entry-level,FT,Computer Vision Engineer,10000,USD,10000,PT,100,LU,Medium
606,606,2022,Mid-level,FT,AI Scientist,200000,USD,200000,IN,100,US,Large

In [75]:
df.loc[df['employee_residence'] != df['company_location']].shape[0]

51

In [77]:
#Group the data by experience_level and calculate the mean, median, and standard deviation of salary_in_usd for each level.
df.groupby('experience_level')['salary_in_usd'].mean()
df.groupby('experience_level')['salary_in_usd'].median()
df.groupby('experience_level')['salary_in_usd'].std()

experience_level
Entry-level         61643.318182
Executive-level    199392.038462
Mid-level           87996.056338
Senior-level       138617.292857
Name: salary_in_usd, dtype: float64

In [78]:
#Extend sol 1
df.groupby('experience_level')['salary_in_usd'].describe()

,count,mean,std,min,25%,50%,75%,max
experience_level,,,,,,,,
Entry-level,88.0,61643.318182,44395.541126,4000.0,27505.0,56500.0,85425.75,250000.0
Executive-level,26.0,199392.038462,117071.255697,69741.0,130006.5,171437.5,233750.00,600000.0
Mid-level,213.0,87996.056338,63901.057478,2859.0,48000.0,76940.0,112000.00,450000.0
Senior-level,280.0,138617.292857,57691.978337,18907.0,100000.0,135500.0,170000.00,412000.0

In [80]:
#Extend sol 2 : use agg function
df.groupby('experience_level')['salary_in_usd'].agg(['mean','median','std'])

                           mean    median            std
experience_level
Entry-level        61643.318182   56500.0   44395.541126
Executive-level   199392.038462  171437.5  117071.255697
Mid-level          87996.056338   76940.0   63901.057478
Senior-level      138617.292857  135500.0   57691.978337

In [83]:
#Calculate the average salary_in_usd for each work_year. 
#Did the average salary increase or decrease from 2020 to 2022?
work_year = df.groupby('work_year')['salary_in_usd'].mean()
print(work_year.loc[2022]- work_year.loc[2020])

28709.006289308178

In [87]:
#Create a pivot table showing the median salary_in_usd where the rows are experience_level and the columns are company_size.
data = pd.pivot_table(df, index = 'experience_level',
                columns = 'company_size', values = 'salary_in_usd', 
                aggfunc = 'median')
print(data)

company_size         Large    Medium     Small
experience_level
Entry-level        63831.0   49823.0   60000.0
Executive-level   196979.0  171437.5  118187.0
Mid-level          86000.0   78658.5   56738.0
Senior-level      147000.0  135500.0  108603.5

In [89]:
#Group by company_location and employment_type. Find the number of employees (count) and the maximum salary in USD for each combination. 
df_grouped = df.groupby(['company_location', 'employment_type']).agg(employee_num=('salary_in_usd', 'count'),
                                                                     max_salary=('salary_in_usd','max'))
df_grouped.sort_values(by='max_salary', ascending = False)
#Sort the results to show the locations with the highest max salaries at the top.

                                  employee_num  max_salary
company_location employment_type
US               FT                        346      600000
                 CT                          4      416000
JP               FT                          6      260000
RU               FT                          2      230000
CA               FT                         30      225000
...                                        ...         ...
ES               PT                          1       10354
KE               FT                          1        9272
IN               PT                          1        5409
IR               FT                          1        4000
VN               FT                          1        4000

[61 rows x 2 columns]

In [97]:
#Use np.where() to create a new Boolean column called is_highly_paid. 
#Set it to True if the salary_in_usd is above the 75th percentile of the entire dataset, and False otherwise.
# df['salary_in_usd'].describe()
df['salary_in_usd'].quantile(0.75) #got 150000 from run this code

df['is_highly_paid'] = np.where(df['salary_in_usd'] > 150000, True, False)
df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,is_highly_paid
0,0,2020,Mid-level,FT,Data Scientist,70000,EUR,79833,DE,0,DE,Large,False
1,1,2020,Senior-level,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,Small,True
2,2,2020,Senior-level,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,Medium,False
3,3,2020,Mid-level,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,Small,False
4,4,2020,Senior-level,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,Large,False

In [98]:
df.loc[(df['salary_in_usd'] > 150000) & (df['is_highly_paid'] == False)]

Empty DataFrame
Columns: [Unnamed: 0, work_year, experience_level, employment_type, job_title, salary, salary_currency, salary_in_usd, employee_residence, remote_ratio, company_location, company_size, is_highly_paid]
Index: []

In [105]:
#Use np.select() or pandas pd.cut() 
#to create a new column called salary_tier that categorized salary_in_usd into three bins:
#apply condition from the notion
condition_lst = [df['salary_in_usd'] < 50000, 
                 (df['salary_in_usd'] >= 50000) & (df['salary_in_usd'] <= 150000),
                df['salary_in_usd'] > 150000]
salary_tier = ['Low','Medium','High']

df['salary_tier'] = np.select(condition_lst, salary_tier, default = 'Unknown')
df

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,is_highly_paid,salary_tier
0,0,2020,Mid-level,FT,Data Scientist,70000,EUR,79833,DE,0,DE,Large,False,Medium
1,1,2020,Senior-level,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,Small,True,High
2,2,2020,Senior-level,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,Medium,False,Medium
3,3,2020,Mid-level,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,Small,False,Low
4,4,2020,Senior-level,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,Large,False,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,602,2022,Senior-level,FT,Data Engineer,154000,USD,154000,US,100,US,Medium,True,High
603,603,2022,Senior-level,FT,Data Engineer,126000,USD,126000,US,100,US,Medium,False,Medium
604,604,2022,Senior-level,FT,Data Analyst,129000,USD,129000,US,0,US,Medium,False,Medium
605,605,2022,Senior-level,FT,Data Analyst,150000,USD,150000,US,100,US,Medium,False,Medium
606,606,2022,Mid-level,FT,AI Scientist,200000,USD,200000,IN,100,US,Large,True,High

In [106]:
df['salary_tier'].value_counts()

salary_tier
Medium    358
High      147
Low       102
Name: count, dtype: int64

In [110]:
#Create a new column called is_expat that contains Trye if the employee_residence does not equal the company_location, and False if they match. 
#What is the average salary of an expat vs. a local?
df['is_expat'] = df['employee_residence'] != df['company_location']
df.groupby('is_expat')['salary_in_usd'].mean()

In [114]:
#Filter the data to only include companies located in the US (US), UK (GB), and Canada (CA). 
#For these three countries, calculate the percentage of roles that are fully remote 
#(remote_ratio == 100) versus not fully remote.
countries = ['US','GB','CA']

df_countries = df.loc[df['company_location'].isin(countries)]
df_countries['remote_ratio'].apply(lambda x: x == 100).value_counts(normalize = True)

remote_ratio
True     0.699074
False    0.300926
Name: proportion, dtype: float64

In [124]:
#Which 5 job_titles have the highest median salary? 
#(Ensure you only consider job titles that appear at least 5 times 
#in the dataset to avoid outliers skewing the data).
job_num = df['job_title'].value_counts() >= 5
atleast5 = job_num[job_num].index

df_sel_job = df[df['job_title'].isin(atleast5)]
df_sel_job.groupby('job_title')['salary_in_usd'].median().sort_values(ascending = False).head(5)

job_title
Head of Data                200000.0
Data Architect              180000.0
Principal Data Scientist    173762.0
Director of Data Science    168000.0
Applied Data Scientist      157000.0
Name: salary_in_usd, dtype: float64

In [127]:
#Does working fully remotely (remote_ratio = 100) pay more than working completely in-person (remote_ratio = 0)? 
#Calculate the median salary for both groups, but do this separately for each experience_level
df[(df['remote_ratio'] == 0) | (df['remote_ratio'] ==100) ].groupby(['experience_level','remote_ratio'])['salary_in_usd'].median().unstack()

remote_ratio           0         100
experience_level
Entry-level        51660.5   59102.0
Executive-level   141846.0  187500.0
Mid-level          74000.0   87000.0
Senior-level      138200.0  140000.0